### ISSUE TITLE
meta tags are not showing in view page resource

### ISSUE THREAD

**Issue by Sakthi002** [troxler/vue-headful#11]

**Comment by troxler** [comment]
Can you be more specific? Do you use server-side rendering or prerendering?

**Comment by Sakthi002** [comment]
I am using Vue with laravel and i rendering all my vue components in one blade file.

**Comment by Sakthi002** [comment]
![Screenshot (52)](https://user-images.githubusercontent.com/35330401/54348065-4802ca00-466e-11e9-8a70-899eef6b5009.png)

**Comment by Sakthi002** [comment]
![seo](https://user-images.githubusercontent.com/35330401/54348169-813b3a00-466e-11e9-8be6-66197970cef5.PNG)

**Comment by Sakthi002** [comment]
![Reso](https://user-images.githubusercontent.com/35330401/54348270-b051ab80-466e-11e9-9946-579aa1641fc5.PNG)

**Comment by troxler** [comment]
I don't see any `<meta name="description"/>` (or similar) in your code. vue-headful does not add any meta elements to the DOM, it only updates attributes if the elements are already in the DOM. In addition to that, both `title` and `description` seem to be undefined in your example.

**Comment by Sakthi002** [comment]
thank you.
