### ISSUE TITLE
How can I solve error Could not find a declaration file for module 'vue-headful'?

### ISSUE THREAD

**Issue by positivethinking639** [troxler/vue-headful#13]
The full error like this :

Could not find a declaration file for module 'vue-headful'. '/Users/chelsea/Documents/website/my-website/node_modules/vue-headful/dist/vue-headful.js' implicitly has an 'any' type.
  Try `npm install @types/vue-headful` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-headful';`ts(7016)

I try to run `npm install @types/vue-headful` to solve this error, but there exist error 👍 
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fvue-headful - Not found
npm ERR! 404 
npm ERR! 404  '@types/vue-headful@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
`

How can I solve this problem?

Note :
- I use vueitfy(Javascript). No typescript

**Comment by troxler** [comment]
> Could not find a declaration file for module 'vue-headful'. '/Users/chelsea/Documents/website/my-website/node_modules/vue-headful/dist/vue-headful.js' implicitly has an 'any' type.
Try npm install @types/vue-headful if it exists or add a new declaration (.d.ts) file containing declare module 'vue-headful';ts(7016)

That is not an error, just an info from your editor. You do not have to do anything about it.

>     npm install @types/vue-headful

vue-headful does not use TypeScript and hence does not have any types.

Just ignore the info and it will be fine.

**Comment by positivethinking639** [comment]
@troxler Okay thanks. I'm just afraid there will be problems going forward if I don't fix this

**Comment by troxler** [comment]
There won't be any problems, it is not an error but just an info.

**Comment by positivethinking639** [comment]
@troxler Great. Thank you very much
