### ISSUE TITLE
problem setting og head properties

### ISSUE THREAD

**Issue by mikecobb-io** [troxler/vue-headful#14]
I cannot set various og head properties. The following meta values all get set apart from og:url and twitter,url

`
<vue-headful

      :title="title"

      :description="description"

      :keywords="keywords"

      :og:description="description"

      :og:url="url"

      :twitter.url="url"

 />
`

It doesn't matter what value I pass to `og:url` it remains empty. I have also tried ogUrl but still no joy. Any help appreciated.

**Comment by troxler** [comment]
Please have a look at the [documentation](https://github.com/troxler/headful#documentation). The properties `og:url` and `twitter.url` just don't have any meaning for (vue-)headful. But you can set the corresponding tags with the `url` attribute like `<vue-headful :url="url"/>`.
