### ISSUE TITLE
Change all ALT

### ISSUE THREAD

**Issue by aleffff** [troxler/vue-headful#16]
Why change all alt of page?

**Comment by troxler** [comment]
I'm not sure what you mean. Can you elaborate? Ideally, provide a code example.

**Comment by aleffff** [comment]
https://prnt.sc/v8wd2a

See image, a tooltip was added to the entire site.

**Comment by troxler** [comment]
Please provide a code example. I can't do anything from a screenshot alone.

**Comment by aleffff** [comment]
You can finish the issue, I will not use the library anymore. Thanks.
