### ISSUE TITLE
Bug: version 1.1.0 breaks if unless you set head and html props to empty object

### ISSUE THREAD

**Issue by wsmcnaughton** [troxler/vue-headful#3]
As I stated in the title, the latest version breaks the package unless you explicitly set head and html props to empty objects. This is a result of the changes made to `vue-headful.js` in commit https://github.com/troxler/vue-headful/commit/77e11fa78a01f0229f952442f778278154f83e6d.

#### Error log from console:
![image](https://user-images.githubusercontent.com/8725263/38261523-178bf17e-3730-11e8-822e-a365fbd7daac.png)

**Comment by troxler** [comment]
@NaughtyMC Thank you for the report. This indeed was a bug that was introduced with the latest changes.

I just pushed version 1.0.2 ([changes](https://github.com/troxler/headful/commit/c9be77a13855bf09cd2a5f5addd99e6dde28c6be)) of [Headful](https://github.com/troxler/headful) to fix the handling of `undefined`/`null` values.

You should be able to upgrade Headful using `npm --depth 1 update`.

Sorry for the inconvenience.
