### ISSUE TITLE
meta tag is show in source code

### ISSUE THREAD

**Issue by patelsujal** [troxler/vue-headful#9]
i am developing vue + laravel website. i am developing front end with only pure vue. i want to set seo meta tags on vue component but this plugin is only set title not meta tags. it is show only on inspect but not showing on view source.

**Comment by troxler** [comment]
See https://github.com/troxler/headful:

> Important: Most properties supported by Headful are only useful when they are set before the browser executes the JavaScript. For example, you won't be able to change properties used for URL sharing on social networks (e.g. Facebook, Twitter) or messengers (WhatsApp, Telegram). That means you should either prerender your pages before the deployment or use server-side rendering.

**Comment by Sakthi002** [comment]
meta tags are not showing in view page resource
